### ISSUE TITLE
Can't delete or modify interrupts?

### ISSUE THREAD

**Issue by cs2dsb** [stm32-rs/stm32-rs#163]
Hey! I'm working on generating patches from the cube mx db to fix the interrupts for the stm32f411 but I can't find a way to delete or modify interrupts in a yaml patch.

The readme suggests 
```
ADC_Common:
  _modify:
     _interrupts: 
      FPU: 
        value: 123
```
but that doesn't seem to work.

I've also tried 
```
ADC_Common:
  _delete:
    _interrupts:
      *
```
and various other permutations.

From a brief look at the python it looks like deleting interrupts isn't intended functionality and I can't see how the modify would work on interrupts either but I'm not a fan of python so I could well have missed something.

The SVD for the 411 seems to be a mess, it makes me wonder how STM generate them. How you can have the FPU interrupt under the ADC_Common peripheral if it's being generated from a database I have no idea; I've got to conclude they've got some intern manually editing them to match some other system.

Cheers!
