### ISSUE TITLE
STM32G4 FDCAN Interrupts are swapped

### ISSUE THREAD

**Issue by romixlab** [stm32-rs/stm32-rs#456]
FDCAN1_INTR0_IT and FDCAN1_INTR1_IT are swapped (seems to be an error from the ST), what would be the best way to fix this?

**Comment by adamgreig** [comment]
It should be possible to create a new file in `devices/common_patches` that looks something like:

```
EXTI:
  _modify:
    _interrupts:
      FDCAN1_INTR0_IT:
        value: 21
      FDCAN1_INTR1_IT:
        value: 22
```

...and then include it in the relevant stm32g4*.yaml device files. You can read about the format for the YAML files (and where `_interrupts` can be used) [here](https://github.com/stm32-rs/svdtools).

While you were at it, it might be worth moving the interrupt to the actual FDCAN or FDCAN1 peripheral instead, by deleting it from EXTI and adding it to the relevant peripheral. And I guess it's worth double checking the other FDCAN interrupts.

Does that make sense? I'm happy to provide more specific help putting a PR together if it's not clear.
