### ISSUE TITLE
STM32F413 vector table is missing the OTG_FS interrupt.

### ISSUE THREAD

**Issue by matoushybl** [stm32-rs/stm32-rs#469]
Just stumbled upon this, I would like to help with it but I don't know where to start. Could you please point me to the right direction?

**Comment by adamgreig** [comment]
Thanks for reporting! Inside the `devices/stm32f413.yaml` file, you'd add something like:

```
OTG_FS:
  _add:
    _interrupts:
      OTG_FS:
        description: USB OTG FS Interrupt
        value: <interrupt number here>
```
