### ISSUE TITLE
STM32F469 seem to miss the DSI global IRQ

### ISSUE THREAD

**Issue by jonasdn** [stm32-rs/stm32-rs#487]
In the `stm32f469xx.h` header file it is defined as:
```
DSI_IRQn = 92      /*!< DSI global Interrupt */
```
But it does not seem to be included here. How would I go about including it?

**Comment by jonasdn** [comment]
It does not seem to be a part of the stm32f69xx svd.

**Comment by wallacejohn** [comment]
I think it requires adding something like this to `stm32f469.yaml`:

```yaml
DSIHOST:
  _add:
    _interrupts:
      DSIHOST:
        description: DSI host global interrupt
        value: 92
```

I could be wrong. I can open a PR if no one else jumps on it.
