### ISSUE TITLE
STM32H753 has 3 bits of wwdg prescaler while only 2 are in the pac

### ISSUE THREAD

**Issue by diondokter** [stm32-rs/stm32-rs#501]
Datasheet of the H742/H743/H753/H750:
![image](https://user-images.githubusercontent.com/8545127/108497465-c41ad900-72ab-11eb-85e1-b88ce9f5eded.png)

Config: https://github.com/stm32-rs/stm32-rs/blob/master/peripherals/wwdg/wwdg.yaml

This has been mentioned in an H7 HAL PR comment, but is seems it wasn't fixed: https://github.com/stm32-rs/stm32h7xx-hal/pull/10/files#r294054557

I don't know how this crate works, so if somebody can instruct me with the rough steps, I could do it.

**Comment by adamgreig** [comment]
Thanks for the report! There are two parts to the fix: first patching the SVD to increase the field width from 2 to 3 bits, and second adding extra enumeration variants. For the first, something like (untested):

```yaml
WWDG:
  CFG:
    _modify:
      WDGTB:
        bitWidth: 3
```

This could go into a new file like `devices/common_patches/h7_wwdg.yaml`, and be added to any H7 that has this problem, or you could just add it to `devices/stm32h753.yaml` to fix it just on this chip (if it doesn't affect other H7s).

The second part is slightly more annoying. The simplest option is probably to make an extra file in `peripherals/wwdg/wwdg_3bit_wdgtb.yaml` that contains something like:

```yaml
WWDG:
    CFG:
        WDGTB:
            _replace_enum:
                Div1: [0, "Counter clock (PCLK div 4096) div 1"]
                Div2: [1, "Counter clock (PCLK div 4096) div 2"]
                Div4: [2, "Counter clock (PCLK div 4096) div 4"]
                Div8: [3, "Counter clock (PCLK div 4096) div 8"]
                Div16: [4, "Counter clock (PCLK div 4096) div 16"]
                <etc>
```

and then include it anywhere that also includes the larger register.
