### ISSUE TITLE
H743 and H743 DFSDM offsets wrong

### ISSUE THREAD

**Issue by David-OConnor** [stm32-rs/stm32-rs#636]
The offsets appear to be correct for all other H743 variants. They all appear to be wrong on H743 and H743V. Working on a fix, but can't get changes to take ATM.

Attempting to apply a common patch of the form:

```yaml
DFSDM:
  _modify:
    DFSDM_CHCFG0R1: 
      addressOffset: 0x00
    DFSDM_CHCFG0R2: 
      addressOffset: 0x04
    DFSDM_AWSCDR0R:
      addressOffset: 0x08
    DFSDM0_DAT0R:
      addressOffset: 0x0C
    DFSDM0_DATIN0R:
      addressOffset: 0x10

    DFSDM_CHCFG1R1: 
      addressOffset: 0x20
    DFSDM_CHCFG1R2: 
      addressOffset: 0x24
    DFSDM_AWSCDR1R:
      addressOffset: 0x28
    DFSDM0_DAT1R:
      addressOffset: 0x2C
    DFSDM0_DATIN1R:
      addressOffset: 0x30.
..
```

Additionally, the SVD names don't match the form of the RM. Eg `FLT0CR2` vs ` DFSDM0_CR2` and `CH2CFGR1` vs `DFSDM_CHCFG0R1`

Also, indexed channels and filters would be nice, eg H7's DMA streams. I'm going to take a stab at the wrong addresses. Any ideas why the fixes I put in aren't taking?
