### ISSUE TITLE
Incorrect stm32f401 PLLN field range constraint

### ISSUE THREAD

**Issue by lynaghk** [stm32-rs/stm32-rs#651]
The constraint is set here: https://github.com/stm32-rs/stm32-rs/blob/883179c90f2f9018c6f1f3d1080bbb562e6ca7eb/peripherals/rcc/rcc_v2.yaml#L24

Which is correct for f405 and f411, but not for f401, where the lower bound is 192 rather than 50:
<img width="793" alt="Screen Shot 2021-10-24 at 10 40 32 PM" src="https://user-images.githubusercontent.com/147919/138640356-b70163e8-08d1-4a81-8301-4917d3f6ca5f.png">

I tried patching at the bottom of https://github.com/stm32-rs/stm32-rs/blob/883179c90f2f9018c6f1f3d1080bbb562e6ca7eb/devices/stm32f401.yaml with one of the following three forms, but none of them actually changed the write constraint.
I suspect it has something to do with the fact that PLLN isn't an SVD field and is being created by some other machinery in svdtools.

```yaml
RCC:
  PLLCFGR:
    _modify:
      PLLN: [192, 432]

RCC:
  PLLCFGR:
    _modify:
      _merge: ["PLLN*"]
      PLLN: [192, 432]

RCC:
  PLLCFGR:
    _modify:
      PLLN: 
        _write_constraint: [192, 432]
```
