### ISSUE TITLE
Allow regex on `_modify` block

### ISSUE THREAD

**Issue by octronics** [stm32-rs/stm32-rs#76]
A use case:
On DBG peripheral registers some field are prefixed with the peripheral name (`DBG_`). I want to remove the prefix to provide better name. Writing all the fields that need patching by hand is not an option. They are numerous, not always present (not a problem as _modify don't bell on absent fields).

Allowing to use regex matches will allow to express this requirements as follow:
```yaml
DBG:
  "APB1_FZ":
    _modify:
     "DBG_(.*)":
       name: "$1"
```
It can be used elsewhere specially on H7 family that has so much registers to rename.
What are your feelings about this idea?
