### ISSUE TITLE
[Discussion] variant name of `MSK*` are misleading

### ISSUE THREAD

**Issue by eZioPan** [stm32-rs/stm32-rs#830]
https://github.com/stm32-rs/stm32-rs/blob/371fc811387c760f3b92e030aa7c68d3250b3ba8/peripherals/rtc/rtc_common.yaml#L158-L160

In my opinion, value `0` should have `NotMasked` variant, and value `1` should have `Masked`, which is also aligned with NVIC concept: mask if deactivate, unmask if activate.

Or even better, I suggest to use

```yaml

 "MSK1": Alarm seconds mask
   ToMatch: [0, "Alarm set if the date/day match"] 
   NotCare: [1, "Seconds don’t care in Alarm comparison"] 
```

to make this values more clearly.

But this modification will break current api, so maybe we need more discussion on it?

and also, `MSK1` ~ `MSK4` share the same description, which is not correct, and need to be too.
